Scrapper, Anna Egorova - 21FPL1
fipl-hse/2022-2-level-ctlr pull request #33
Opened 2023-04-02 14:57 UTC by chezar0

2023-04-05 06:05 UTC, marina-kaz reviewed
The 5th laboratory work is expected to be implemented in the 'lab_5_scrapper' folder, so please remove `main.py` file from core utils folder, thank you!

2023-04-10 13:13 UTC, marina-kaz reviewed
Please, remove `main.py` from `core_utils`

2023-04-12 12:01 UTC, marina-kaz reviewed
It is a solid start, keep going

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        with open(self.path_to_config, 'r', encoding='utf-8') as f:
`f` is not a good variable name

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        with open(self.path_to_config, 'r', encoding='utf-8') as f:
use `_extract_config_content` or corresponding attributes instead of reading a file all over again

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        for url in parameters['seed_urls']:
what if it is not iterable or empty

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        if parameters['total_articles_to_find_and_parse'] not in range(1, 150):
use predefined constants to denote the limits

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        if parameters['timeout'] > 60 or parameters['timeout'] < 0:
use predefined constants to denote the limits

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +            #raise IncorrectVerifyError
`IncorrectVerifyError` should also be thrown in the appropriate cases

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +    return requests.get(url,
also set the encoding and `verify_certificate` parameters

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +            response = requests.get(url, self._config)
use `make_request` function

2023-04-12 12:01 UTC, marina-kaz commented on lab_5_scrapper/scrapper.py
> +        self.config = config
consider making it non-public

2023-04-12 21:41 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        with open(self.path_to_config, 'r', encoding='utf-8') as f:
fixed

2023-04-12 21:41 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        with open(self.path_to_config, 'r', encoding='utf-8') as f:
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        for url in parameters['seed_urls']:
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        if parameters['total_articles_to_find_and_parse'] not in range(1, 150):
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        if parameters['timeout'] > 60 or parameters['timeout'] < 0:
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +            #raise IncorrectVerifyError
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +    return requests.get(url,
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +            response = requests.get(url, self._config)
fixed

2023-04-12 21:42 UTC, chezar0 commented on lab_5_scrapper/scrapper.py
> +        self.config = config
fixed

2023-04-14 06:33 UTC, demid5111 requested changes

2023-04-14 06:33 UTC, demid5111 commented on core_utils/article/article.py
> -        Sets POS frequencies attribute
keep PR cleaned

2023-04-14 06:33 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +                            timeout=config.get_timeout(),
what is it?

2023-04-19 10:53 UTC, dmitry-uraev requested changes

2023-04-19 10:53 UTC, dmitry-uraev commented on lab_5_scrapper/scrapper.py
> +        #topics_info = article_soup.find_all('a', class_='article__tags')
why do no try for score 8?

2023-04-22 08:40 UTC, vitazaytseva commented
Well done! You can proceed to work on Lab 6)

2023-04-22 08:40 UTC, closed without merging