Scrapper, Sofya Kostina - 21FPL2
fipl-hse/2022-2-level-ctlr pull request #43
Opened 2023-04-06 17:08 UTC by d07l

2023-04-11 09:06 UTC, dmitry-uraev requested changes
It is right time to start implementing lab_5!

2023-04-19 10:29 UTC, dmitry-uraev requested changes
You have implementation for score 4 according to your target score. It means that if you pass lab handover, you still get no more than 3. May be you want to increase target score and write some additional logic?

2023-04-19 10:29 UTC, dmitry-uraev commented on lab_5_scrapper/scrapper.py
> +    #time.sleep(random.randint(2,5))
is this needed or no?

2023-04-19 10:29 UTC, dmitry-uraev commented on lab_5_scrapper/scrapper.py
> +            elif link[16:26] == '/news/2023':
can you simplify this check?

2023-04-20 21:39 UTC, d07l commented on lab_5_scrapper/scrapper.py
> +    #time.sleep(random.randint(2,5))
no, removed

2023-04-20 21:40 UTC, d07l commented on lab_5_scrapper/scrapper.py
> +            elif link[16:26] == '/news/2023':
yes, I did it

2023-04-21 08:08 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    #time.sleep(random.randint(2,5))
keep

2023-04-22 08:37 UTC, vitazaytseva commented
Well done! You can proceed to work on Lab 6)

2023-04-22 08:37 UTC, closed without merging