Scrapper, Alexandra Eliseeva - 21FPL1
fipl-hse/2022-2-level-ctlr pull request #50
Opened 2023-04-08 11:55 UTC by Tasenko03

2023-04-10 19:00 UTC, demid5111 requested changes
hurry up, progress is nice, but time is going

2023-04-10 19:00 UTC, demid5111 commented on requirements.txt
> +requests==2.28.2
where are changes in config.json?

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/target_score.txt
> +4
too small

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +        href = article_bs.get('href')
unnecessary variable

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    time.sleep(random.randint(TIMEOUT_LOWER_LIMIT, TIMEOUT_UPPER_LIMIT))
nice! 🏅

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    return response
set encoding before return

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +            if not re.match(re.compile(r"https?://w?w?w?."), url):
do you think it is possible to have for example just one w?

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +        with open(self.path_to_config, 'r', encoding='utf-8') as f:
duplicated read

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +        self._validate_config_content()
in init:

1. you need to extract config's content with a function
2. run validation using DTO from the previuos step
3. fill attributes of config and continue work

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +        seed_urls = config['seed_urls']
rework validation to operate on top of DTO instance

2023-04-10 19:00 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
>  def main() -> None:
add demonstration logic, ensure it will be able to collect 100 articles

2023-04-12 13:27 UTC, demid5111 requested changes
some more work is required. keep going

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +            if not re.match(re.compile(r"https?://w?."), url):
now you accept sites like http://w.google.com is that correct?

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +    time.sleep(random.randint(TIMEOUT_LOWER_LIMIT, TIMEOUT_UPPER_LIMIT))
but now I see that it is a bit wrong. timeout like `TIMEOUT_UPPER_LIMIT` should be used in checks, not here. here you need to provide some random sleep in range of 1-3

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +            driver = webdriver.Chrome(executable_path="C:\\Users\\Ольга\\Desktop\\2022-2-level-ctlr\\chrome "
???

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +                                              "driver\\chromedriver_win32\\chromedriver.exe")
1. discard dynamic crawling
2. even if you want (and I wholeheartedly convince you to give up) such paths specific to your machine will never work in CI

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper.py
> +            paragraphs += " ".join([text.get_text(strip=True) for text in par])
join once, avoid string concatenation

2023-04-12 13:27 UTC, demid5111 commented on lab_5_scrapper/scrapper_config.json
>      "headers": {},
where are haeaders

2023-04-12 23:41 UTC, Tasenko03 commented on lab_5_scrapper/scrapper.py
> +    return response
Done

2023-04-12 23:42 UTC, Tasenko03 commented on requirements.txt
> +requests==2.28.2
Added

2023-04-12 23:43 UTC, Tasenko03 commented on lab_5_scrapper/scrapper.py
> +        self._validate_config_content()
Done

2023-04-14 06:24 UTC, demid5111 requested changes
https://prmira.ru/news/2023-04-13/tsifrovoy-bank-tochka-vystavlen-na-prodazhu-2902423 not all text collected

2023-04-20 08:28 UTC, demid5111 commented
nothing to review to this moment

2023-04-22 08:34 UTC, vitazaytseva commented
Well done! You can proceed to work on Lab 6)

2023-04-22 08:34 UTC, closed without merging