Pipeline, Lopatko Yulia - 21FPL1
fipl-hse/2022-2-level-ctlr pull request #67
Opened 2023-04-21 06:37 UTC by lazykosti

2023-04-26 18:32 UTC, dmitry-uraev requested changes
Good start for pipeline. Please continue work

2023-05-03 19:55 UTC, dmitry-uraev commented
No progress since last review

2023-05-08 12:17 UTC, dmitry-uraev commented
No progress since last review

2023-05-10 18:10 UTC, dmitry-uraev approved these changes

2023-05-10 18:11 UTC, dmitry-uraev commented
You are done for score 4 now

2023-05-15 18:44 UTC, dmitry-uraev reviewed
Good job! Let's pass CI checks

2023-05-15 18:44 UTC, dmitry-uraev commented on lab_6_pipeline/pipeline.py
> +        }
is it necessary to define pos_feats structure like this explicitly?

2023-05-15 18:49 UTC, lazykosti commented on lab_6_pipeline/pipeline.py
> +        }
nope! I give up anyway. So I guess I'm going to close PR now
Thank you for 4 :)

2023-05-15 18:51 UTC, closed without merging